version: "3.8"
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: KartavyaPortfolioAI
    environment:
      - cluster.name=KartavyaPortfolioAI-cluster
      - node.name=KartavyaPortfolioAI
      - plugins.security.disabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.allow_rebalance=always
      - cluster.routing.allocation.enable=all
      - cluster.routing.allocation.node_concurrent_recoveries=2
      - cluster.routing.allocation.disk.threshold_enabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://KartavyaPortfolioAI:9200"]
    ports:
      - "5601:5601"
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
